openapi: 3.0.0
info:
  title: API Мобильного приложения
  version: 1.0.0
  description: API Мобильного приложения
paths:
  /signup:
    post:
      summary: 'Создает нового пользователя или ищет существующего пользователя по номеру телефона.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone_number:
                  type: string
            examples:
              example1:
                value:
                  phone_number: '1234567890'
      responses:
        '200':
          description: 'Успешный ответ'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 'Сгенерированный OTP-код. Присутствует до добавления смс-сервиса'

            examples:
              example1:
                value:
                  message: '123456'

        '422':
          description: 'Ошибка валидации или другие ошибки'
  /login:
    post:
      summary: 'Авторизует пользователя с помощью номера телефона и OTP-кода.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone_number:
                  type: string
                code:
                  type: string
            examples:
              example1:
                value:
                  phone_number: '1234567890'
                  code: '123456'
      responses:
        '200':
          description: 'Успешный ответ'
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: 'Токен доступа'
                  refresh_token:
                    type: string
                    description: 'Токен обновления'
                  new_user:
                    type: boolean
                    description: 'Признак нового пользователя'
            examples:
              example1:
                value:
                  token: 'access_token'
                  refresh_token: 'refresh_token'
                  new_user: true
        '401':
          description: 'Ошибка авторизации'
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                example1:
                  value:
                    error: 'Invalid code'
  /user:
    get:
      summary: Получение данных профиля пользователя
      description: Возвращает информацию о профиле текущего пользователя.
      tags:
        - Профиль пользователя
      responses:
        '200':
          description: Данные профиля успешно получены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
            examples:
              example1:
                value:
                  user_id: 123
                  first_name: 'John'
                  country: 'USA'
                  city: 'New York'
                  birthday: '1990-01-01'
                  email: 'john@example.com'
                  verified_email: true
    post:
      summary: Установка данных профиля пользователя
      description: Создает информацию о профиле текущего пользователя.
      tags:
        - Профиль пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfoUpdate'
            examples:
              example1:
                value:
                  first_name: 'Jane'
                  country: 'Canada'
                  city: 'Toronto'
                  birthday: '1995-02-15'
                  email: 'jane@example.com'
      responses:
        '200':
          description: Данные профиля успешно созданы
        '400':
          description: Некорректный запрос
    put:
      summary: Обновление данных профиля пользователя
      description: Обновляет информацию о профиле текущего пользователя.
      tags:
        - Профиль пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfoUpdate'
            examples:
              example1:
                value:
                  first_name: 'Jane'
                  country: 'Canada'
                  city: 'Toronto'
                  birthday: '1995-02-15'
                  email: 'jane@example.com'
      responses:
        '200':
          description: Данные профиля успешно обновлены
        '400':
          description: Некорректный запрос
    security:
      - BearerAuth: []

  /main:
    get:
      summary: Получение информации для главной страницы
      description: Данные о товарах и акциях для главной страницы
      tags:
        - Главная страница
      responses:
        '200':
          description: 'Успешный ответ'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MainPage'
              examples:
                example1:
                  value:
                    mainPage:
                      banners:
                        - id: 1
                          title: 'Заголовок баннера'
                          image: 'url_изображения_баннера'
                          link: 'ссылка_баннера'
                        - id: 2
                          title: 'Другой баннер'
                          image: 'url_изображения_другого_баннера'
                          link: 'ссылка_другого_баннера'
                      categories:
                        - id: 1
                          name: 'Категория 1'
                          products:
                            - id: 1
                              name: 'Название продукта 1'
                              description: 'Описание продукта 1'
                              price: 19.99
                              old_price: 29.99
                              images: ['url_изображения_продукта_1_1', 'url_изображения_продукта_1_2']
                              promotions:
                                - id: 1
                                  title: 'Акция 1'
                                  description: 'Описание акции 1'
                            - id: 2
                              name: 'Название продукта 2'
                              description: 'Описание продукта 2'
                              price: 24.99
                              old_price: 29.99
                              images: ['url_изображения_продукта_2_1', 'url_изображения_продукта_2_2']
                              promotions: [ ]
                        - id: 2
                          name: 'Категория 2'
                          products:
                            - id: 3
                              name: 'Название продукта 3'
                              description: 'Описание продукта 3'
                              price: 14.99
                              old_price: 19.99
                              images: ['url_изображения_продукта_3_1', 'url_изображения_продукта_3_2']
                              promotions:
                                - id: 2
                                  title: 'Акция 2'
                                  description: 'Описание акции 2'
                            - id: 4
                              name: 'Название продукта 4'
                              description: 'Описание продукта 4'
                              price: 29.99
                              old_price:
                              image: 'url_изображения_продукта_4'
                              promotions: [ ]

components:
  schemas:
    UserInfo:
      type: object
      properties:
        user_id:
          type: integer
          description: Идентификатор пользователя
        first_name:
          type: string
          description: Имя пользователя
        country:
          type: string
          description: Страна пользователя
        city:
          type: string
          description: Город пользователя
        birthday:
          type: string
          format: date
          description: Дата рождения пользователя
        email:
          type: string
          format: email
          description: Email пользователя
        verified_email:
          type: boolean
          description: Флаг подтверждения email
      required:
        - user_id
        - first_name
        - country
        - city
        - birthday
        - email
        - verified_email

    UserInfoUpdate:
      type: object
      properties:
        first_name:
          type: string
          description: Имя пользователя
        country:
          type: string
          description: Страна пользователя
        city:
          type: string
          description: Город пользователя
        birthday:
          type: string
          format: date
          description: Дата рождения пользователя
        email:
          type: string
          format: email
          description: Email пользователя

    MainPage:
      type: object
      properties:
        banners:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                description: Идентификатор баннера
              title:
                type: string
                description: Текст на банере
              image:
                type: string
                description: url изображения
              link:
                type: string
                description: линка
        categories:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              products:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: string
                    price:
                      type: number
                    old_price:
                      type: number
                    images:
                      type: array
                      items:
                        type: string
                    promotions:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          title:
                            type: string
                          description:
                            type: string